Added Workspace Quick Switcher
ArmA-Studio/ArmA.Studio pull request #25
Opened 2017-04-16 08:44 UTC by vabene1111

## Reason for PullRequest
Especially with the old Workspace File Dialog, but also with the new one, it was a little annoying to always search the Path of the Workspace you wanted to work in, so i added a List with the last 5 (configurable) workspaces a users has used for quick switching.

## Description of the Changes
Added a List Box to the WorkSpace Selector Dialog that Contains the last 5 used workspaces.
Clicking an Item results in it beeing put in the TextBox above and the "ok" button beeing enabled, pressing ok will then open the selected workspace.

## Notes
I have tested the changes with a clean install and also different data and everything seems to work fine.
I have tried to make all changes respecting the wpf mvvm scheme (and the general style of the application), but since i have never used it before there might be mistakes in that, if anything needs to be changed please let me know.

2017-04-16 23:16 UTC, dedmen commented
I don't know if it's the best time to do something like that now. A ton of the workspace stuff will probably change with the new Plugin-System.

2017-04-17 09:29 UTC, X39 requested changes

2017-04-17 09:29 UTC, X39 commented on ArmA.Studio/Properties/Localization.resx
> +    <value>Last Workspaces</value>
Should be "Recent Workspaces" or just "Recent"

2017-04-17 09:29 UTC, X39 commented on ArmA.Studio/Dialogs/WorkspaceSelectorDialogDataContext.cs
> +        public String WorkSpaceListBoxSelectedItem { get { return this._WorkSpaceListBoxSelectedItem; } set { this._WorkSpaceListBoxSelectedItem = value; this.RaisePropertyChanged();  this.WorkSpaceL
Extra field WorkSpaceListBoxSelectedItem should be removed and the SelectedItem can be bound to `CurrentPath` directly

2017-04-17 09:29 UTC, X39 commented on ArmA.Studio/Dialogs/WorkspaceSelectorDialog.xaml
> +        <ListBox Grid.Row="2" Grid.ColumnSpan="3" ItemsSource="{Binding WorkSpaceListBox}" SelectedItem="{Binding WorkSpaceListBoxSelectedItem}" >
Extra field WorkSpaceListBoxSelectedItem should be removed and the SelectedItem can be bound to `CurrentPath` directly

2017-04-17 09:29 UTC, X39 commented on ArmA.Studio/ConfigHost.cs
> +                }
the `{`s should be placed below `get`/`set`

2017-04-17 09:29 UTC, X39 commented on ArmA.Studio/App.xaml.cs
> +
Should be moved into the OK command in `ArmA.Studio/Dialogs/WorkspaceSelectorDialogDataContext.cs`

2017-04-17 12:33 UTC, vabene1111 commented
i will fix @X39 requests tomorrow, if you think its not the best time feel free to just leave it in pending or reject, however you like

2017-04-18 14:14 UTC, X39 approved these changes

2017-04-18 14:14 UTC, merged