Implemented an option to change language
ArmA-Studio/ArmA.Studio pull request #50
Opened 2017-05-25 14:56 UTC by railey1990

## Reason for PullRequest
Implemented a feature which allows you to change the language, as there is no such feature yet.

## Description of the Changes
Added a config entry in the App section of the configfile and a new section in the properties, to be able to change the language during runtime.

## Notes
In order to use the selected language the app has to be restarted.

2017-05-25 15:03 UTC, X39 requested changes
Missing a way to notify the user about required restart

2017-05-25 15:11 UTC, X39 commented
to get a callback, a wrapper item can be created
example:
```cs
using System;

namespace ArmA.Studio.Data.Configuration
{
    public class ChangeCallbackItemWrapper : Item
    {
        public Item InnerItem { get; private set; }
        public Func<object, object> Callback { get; private set; }

        public ChangeCallbackItemWrapper(Item i, Action<object> callback) : this(i, (obj) => { callback(obj); return obj; }) { }
        public ChangeCallbackItemWrapper(Item i, Func<object, object> callback) : base(i.Template, i.Value)
        {
            this.InnerItem = i;
            this.Callback = callback;
        }


        public override bool IsValidValue(object value) => this.InnerItem.IsValidValue(value);

        public override object OnValueChange(object oldValue, object newValue)
        {
            var val = this.InnerItem.OnValueChange(oldValue, newValue);
            val = this.Callback.Invoke(val);
            return val;
        }
    }
}```

2017-05-25 17:06 UTC, railey1990 commented
Implemented dialog which notifies the user and asks him if he wants to restart the app right away

2017-05-25 17:08 UTC, X39 requested changes

2017-05-25 17:08 UTC, X39 commented on ArmA.Studio.Data/Configuration/ComboBoxItem.cs
> +        public Func<object, object> ValueChangeCallback { get; set; } = null;
it is not supposed to add value changed callbacks to Items

use property getter & setter or proxy properties for this

2017-05-25 17:08 UTC, X39 commented on ArmA.Studio/Dialogs/PropertiesDialogDataContext.cs
> +                Application.Current.Exit += ( sender, args ) =>
Please use static function `App.Shutdown(...)` for this

2017-05-25 18:14 UTC, railey1990 commented
Implemented a seperate LanguageManager which handles the logic.

2017-05-26 01:19 UTC, X39 approved these changes

2017-05-26 01:20 UTC, merged